version = "3.11.5"
runner.dialect = scala213
indent.main = 4
indent.callSite = 4
indent.defnSite = 4
indent.caseSite = 4
align.preset = none
maxColumn = 120
newlines.source = keep
docstrings.style = keep
rewrite.rules = []
rewrite.trailingCommas.style = keep
rewrite.trailingCommas.allowFolding = false
project.excludeFilters = [
    ".*/Zircon-2024/.*",
    ".*/Zircon-ASIC/.*",
    ".*/src/test/resources/.*",
    ".*/target/.*",
    ".*/build/.*"
]
